# Service api : test pattern

GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUwNjU4OTg0LCJleHAiOjE3NTE5NTQ5ODR9.07bxYHfaiXlksxy9TI3kwTVqyvuJaZIvzdggLt7sVlk
###
# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
  # "identity" : "1234567894",
  # "identity" : "someone@ggg.mail",
  # "email" : "someone@jjj.mail",
  "mobile" : "1234567893",
  "firstName" : "someone",
  "lastName" : "codecamp",
  "password" : "123456",
  "confirmPassword" : "123456",
  "status" : "good"
}
###
# Login api
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
  # "identity" : "andy@ggg.mail",
  "identity" : "1111111111",
  "password" : "123456"
}
###
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
    "message": "sample message"
}
###




